export const CurriculumCategory = {
  BACKEND_DEVELOPER: "backend_developer",
  FRONTEND_DEVELOPER: "frontend_developer",
  FULLSTACK_DEVELOPER: "fullstack_developer",
  MOBILE_DEVELOPER: "mobile_developer",
  DESKTOP_DEVELOPER: "desktop_developer",
  EMBEDDED_SYSTEMS_DEVELOPER: "embedded_systems_developer",
  GAME_DEVELOPER: "game_developer",
  DATA_ENGINEER: "data_engineer",
  DATA_ANALYST: "data_analyst",
  DATA_SCIENTIST: "data_scientist",
  MACHINE_LEARNING_ENGINEER: "machine_learning_engineer",
  DEVOPS_ENGINEER: "devops_engineer",
  CLOUD_ENGINEER: "cloud_engineer",
  SITE_RELIABILITY_ENGINEER: "site_reliability_engineer",
  CYBERSECURITY_ANALYST: "cybersecurity_analyst",
  QA_ENGINEER: "qa_engineer",
  SOFTWARE_ARCHITECT: "software_architect",
  UI_UX_DESIGNER: "ui_ux_designer",
  PRODUCT_MANAGER: "product_manager",
  SCRUM_MASTER: "scrum_master",

  ADMINISTRATIVE_ASSISTANT: "administrative_assistant",
  ADMINISTRATIVE_ANALYST: "administrative_analyst",
  OFFICE_MANAGER: "office_manager",
  EXECUTIVE_ASSISTANT: "executive_assistant",
  FINANCIAL_ANALYST: "financial_analyst",
  ACCOUNTANT: "accountant",
  CONTROLLER: "controller",
  AUDITOR: "auditor",

  SALES_REPRESENTATIVE: "sales_representative",
  INSIDE_SALES: "inside_sales",
  ACCOUNT_EXECUTIVE: "account_executive",
  ACCOUNT_MANAGER: "account_manager",
  BUSINESS_DEVELOPMENT: "business_development",
  CUSTOMER_SUCCESS_MANAGER: "customer_success_manager",

  MARKETING_ANALYST: "marketing_analyst",
  DIGITAL_MARKETING_SPECIALIST: "digital_marketing_specialist",
  SOCIAL_MEDIA_MANAGER: "social_media_manager",
  SEO_SPECIALIST: "seo_specialist",
  CONTENT_WRITER: "content_writer",
  COPYWRITER: "copywriter",
  GRAPHIC_DESIGNER: "graphic_designer",

  RECRUITER: "recruiter",
  TALENT_ACQUISITION_SPECIALIST: "talent_acquisition_specialist",
  HR_ANALYST: "hr_analyst",
  HR_BUSINESS_PARTNER: "hr_business_partner",

  CIVIL_ENGINEER: "civil_engineer",
  MECHANICAL_ENGINEER: "mechanical_engineer",
  ELECTRICAL_ENGINEER: "electrical_engineer",
  PRODUCTION_ENGINEER: "production_engineer",
  CHEMICAL_ENGINEER: "chemical_engineer",

  PHYSICIAN: "physician",
  NURSE: "nurse",
  PHARMACIST: "pharmacist",
  PHYSIOTHERAPIST: "physiotherapist",
  PSYCHOLOGIST: "psychologist",
  NUTRITIONIST: "nutritionist",
  DENTIST: "dentist",

  TEACHER: "teacher",
  PROFESSOR: "professor",
  PEDAGOGUE: "pedagogue",
  SCHOOL_COORDINATOR: "school_coordinator",

  LAWYER: "lawyer",
  LEGAL_ASSISTANT: "legal_assistant",
  PARALEGAL: "paralegal",

  LOGISTICS_ANALYST: "logistics_analyst",
  SUPPLY_CHAIN_ANALYST: "supply_chain_analyst",
  WAREHOUSE_SUPERVISOR: "warehouse_supervisor",
  PROCUREMENT_SPECIALIST: "procurement_specialist",

  CUSTOMER_SERVICE_REPRESENTATIVE: "customer_service_representative",
  TECHNICAL_SUPPORT_SPECIALIST: "technical_support_specialist",
  HELP_DESK_ANALYST: "help_desk_analyst",

  PRODUCTION_OPERATOR: "production_operator",
  MAINTENANCE_TECHNICIAN: "maintenance_technician",
  INDUSTRIAL_MECHANIC: "industrial_mechanic",
  ELECTRICIAN: "electrician",

  INTERN: "intern",
  TRAINEE: "trainee",
  FREELANCER: "freelancer",
  CONSULTANT: "consultant",
} as const;

export type CurriculumCategory = (typeof CurriculumCategory)[keyof typeof CurriculumCategory];

export const CurriculumCategoryLabel: Record<CurriculumCategory, string> = {
  backend_developer: "Desenvolvedor Backend",
  frontend_developer: "Desenvolvedor Frontend",
  fullstack_developer: "Desenvolvedor Fullstack",
  mobile_developer: "Desenvolvedor Mobile",
  desktop_developer: "Desenvolvedor Desktop",
  embedded_systems_developer: "Desenvolvedor de Sistemas Embarcados",
  game_developer: "Desenvolvedor de Jogos",
  data_engineer: "Engenheiro de Dados",
  data_analyst: "Analista de Dados",
  data_scientist: "Cientista de Dados",
  machine_learning_engineer: "Engenheiro de Machine Learning",
  devops_engineer: "Engenheiro DevOps",
  cloud_engineer: "Engenheiro de Cloud",
  site_reliability_engineer: "Engenheiro SRE",
  cybersecurity_analyst: "Analista de Cibersegurança",
  qa_engineer: "Engenheiro de QA",
  software_architect: "Arquiteto de Software",
  ui_ux_designer: "Designer UI/UX",
  product_manager: "Gerente de Produto",
  scrum_master: "Scrum Master",
  administrative_assistant: "Assistente Administrativo",
  administrative_analyst: "Analista Administrativo",
  office_manager: "Gerente de Escritório",
  executive_assistant: "Assistente Executivo",
  financial_analyst: "Analista Financeiro",
  accountant: "Contador",
  controller: "Controller",
  auditor: "Auditor",
  sales_representative: "Representante de Vendas",
  inside_sales: "Inside Sales",
  account_executive: "Executivo de Contas",
  account_manager: "Gerente de Contas",
  business_development: "Desenvolvimento de Negócios",
  customer_success_manager: "Gerente de Customer Success",
  marketing_analyst: "Analista de Marketing",
  digital_marketing_specialist: "Especialista em Marketing Digital",
  social_media_manager: "Gerente de Redes Sociais",
  seo_specialist: "Especialista em SEO",
  content_writer: "Redator de Conteúdo",
  copywriter: "Copywriter",
  graphic_designer: "Designer Gráfico",
  recruiter: "Recrutador",
  talent_acquisition_specialist: "Especialista em Talent Acquisition",
  hr_analyst: "Analista de RH",
  hr_business_partner: "HR Business Partner",
  civil_engineer: "Engenheiro Civil",
  mechanical_engineer: "Engenheiro Mecânico",
  electrical_engineer: "Engenheiro Eletricista",
  production_engineer: "Engenheiro de Produção",
  chemical_engineer: "Engenheiro Químico",
  physician: "Médico",
  nurse: "Enfermeiro",
  pharmacist: "Farmacêutico",
  physiotherapist: "Fisioterapeuta",
  psychologist: "Psicólogo",
  nutritionist: "Nutricionista",
  dentist: "Dentista",
  teacher: "Professor",
  professor: "Professor Universitário",
  pedagogue: "Pedagogo",
  school_coordinator: "Coordenador Escolar",
  lawyer: "Advogado",
  legal_assistant: "Assistente Jurídico",
  paralegal: "Paralegal",
  logistics_analyst: "Analista de Logística",
  supply_chain_analyst: "Analista de Supply Chain",
  warehouse_supervisor: "Supervisor de Armazém",
  procurement_specialist: "Especialista em Compras",
  customer_service_representative: "Atendente de SAC",
  technical_support_specialist: "Especialista em Suporte Técnico",
  help_desk_analyst: "Analista de Help Desk",
  production_operator: "Operador de Produção",
  maintenance_technician: "Técnico de Manutenção",
  industrial_mechanic: "Mecânico Industrial",
  electrician: "Eletricista",
  intern: "Estagiário",
  trainee: "Trainee",
  freelancer: "Freelancer",
  consultant: "Consultor",
};

export const Language = {
  ENGLISH: "english",
  PORTUGUESE: "portuguese",
  SPANISH: "spanish",
} as const;


export type Language = (typeof Language)[keyof typeof Language];